apply plugin: "com.diffplug.spotless"

spotless {
    java {
        target "src/**/*.java"
        googleJavaFormat()
    }

    kotlin {
        target "src/**/*.kt"
        ktlint()
    }

    format "misc", {
        target "**/*.gradle", "**/*.md", "**/.gitignore"
        trimTrailingWhitespace()
        indentWithSpaces(4)
        endWithNewline()
    }
}
